seed:
  2333
data:
  edh_dir: "data/train/edh/2012"
  era5_dir: "data/train/era5/2012"
  val_ratio: 0.2
  num_workers: 1
  persistent_workers: True
model:
  in_channels: 6
  out_channels: 1
  bilinear: True
  block_out_channels: [64, 128, 256, 512, 1024]
optim:
  accelerator: "gpu"
  precision: "32"
  batch_size: 128
  float32_matmul_precision: "medium"
  method: "adam"
  lr: 1e-3
  betas: [0.5, 0.9]
  gradient_clip_val: 1.0
  max_epochs: 500
  accumulate: 1
  # scheduler
  warmup_percentage: 0.1
  lr_scheduler_mode: "cosine"
  min_lr_ratio: 1.0e-3
  warmup_min_lr_ratio: 0.1
  # early stopping
  monitor: "val_loss"
  patience: 20
