seed: 2333
data:
  edh: "data/train/edh/2018"
  era5: "data/train/era5/2018"
model: 
  params:    
    criterion: 'squared_error'
    max_depth: null
    min_samples_split: 2
    min_samples_leaf: 1
    min_weight_fraction_leaf: 0.0
    max_leaf_nodes: null
    min_impurity_decrease: 0.0
    bootstrap: true
    oob_score: false
    n_jobs: -1
    random_state: null
    verbose: 0
    warm_start: false   
    ccp_alpha: 0.0
  ckp: "ckps/rf/rf-2003-2022.pkl"
optim:
  n_estimators: 2
